---
- name: Install needed dotfiles everywhere
  hosts: all
  remote_user: root
  vars_files:
   - vars/dotfiles_vars.yml

  pre_tasks:
    - name: Create user {{ username }} if does not exists
      user:
        group: "{{ username }}"
        name: "{{ username }}"

  roles:
    - { role: zsh, tags: ['shell'] }
    - vim
    - git
    - tmux
    - { role: dotcommon, tags: ['dotcommon'] }
    - rofi
    - { role: backup, tags: ['backup'] }
