---
- name: Install needed X applications everywhere
  hosts: all
  remote_user: root
  vars_files:
    - vars/xapps.yml

  pre_tasks:
    - name: Create user {{ username }} if does not exists
      user:
        group: "{{ username }}"
        name: "{{ username }}"

  tasks:
    - name: Install needed packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - pycharm-community-edition
