---
- name: Install screen
  package:
    name: screen
    state: latest

- name: Copy .screenrc to user home directory
  copy: src=.screenrc dest=~/.screenrc
  become: yes
  become_user: "{{ username }}"
